### ISSUE TITLE
Watermark opacity not work

### ISSUE THREAD

**Issue by SevenBasic** [iron-software/IronPDF-for-Java#13]
no matter which opacity is defined, the opacity is always 0%.

Code:

 PdfDocument pdf = PdfDocument.renderUrlAsPdf("https://ironpdf.com/", IronUtils.getOptionsWithMargins());
       
        pdf.applyWatermark("<h2 style='color:red'>SAMPLE</h2>",1, VerticalAlignment.MIDDLE, HorizontalAlignment.LEFT);
        pdf.applyWatermark("<h2 style='color:red'>SAMPLE</h2>",30, VerticalAlignment.MIDDLE, HorizontalAlignment.CENTER);
        pdf.applyWatermark("<h2 style='color:red'>SAMPLE</h2>",80, VerticalAlignment.MIDDLE, HorizontalAlignment.RIGHT);

**Comment by ikkyuland** [comment]
Hi @SevenBasic, Thank you for your feedback and sorry for the late reply.
This issue should be fixed in version 2023.7.2

```
 PdfDocument pdf = PdfDocument.renderUrlAsPdf("https://ironpdf.com/");
        pdf.applyWatermark("<h2 style='color:red'>SAMPLEA</h2>",10, VerticalAlignment.MIDDLE, HorizontalAlignment.LEFT);
        pdf.applyWatermark("<h2 style='color:red'>SAMPLEB</h2>",30, VerticalAlignment.MIDDLE, HorizontalAlignment.CENTER);
        pdf.applyWatermark("<h2 style='color:red'>SAMPLEC</h2>",80, VerticalAlignment.MIDDLE, HorizontalAlignment.RIGHT);
        pdf.saveAs("mydoc.pdf");
```
[mydoc.pdf](https://github.com/iron-software/IronPDF-for-Java/files/12425498/mydoc.pdf)
